# Setup
title: SitedeLuis
url: https://sitedeluis.github.io
paginate: 2
paginate_path: "/page:num/"
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-include-cache

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

  # Configuración de idioma
locale: es_ES
timezone: America/Bogota  # Ajusta según tu zona horaria

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Luis

# Custom vars
version: 1.0.0

# Navbar page list
nav:
  - title: Archivo
    url: /archive

  - title: Acerca
    url: /about

feed:
path: "feed.xml"
limit: 8
author: "Luis"
categories: false
license: "https://creativecommons.org/licenses/by-nc-sa/4.0/"
