# Setup
title: SitedeLuis
url: https://sitedeluis.github.io/
paginate: 2
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-pdf-embed
  - jekyll-remote-theme
  - jekyll-include-cache

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Luis

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Archivo
    url: /archive

  - title: Acerca
    url: /about
